//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AtlasSchemaRevisions struct {
	Version         string `sql:"primary_key"`
	Description     string
	Type            int32
	Applied         int32
	Total           int32
	ExecutedAt      time.Time
	ExecutionTime   int32
	Error           *string
	ErrorStmt       *string
	Hash            string
	PartialHashes   *string
	OperatorVersion string
}
