//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type RecipeImages struct {
	ID        *int32 `sql:"primary_key"`
	RecipeID  int32
	Path      string
	SortOrder int32
	CreatedAt time.Time
}
