//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ShoppingListItems struct {
	ID             *int32 `sql:"primary_key"`
	ShoppingListID int32
	Ingredient     string
	Quantity       *string
	Unit           *string
	Done           bool
	SortOrder      int32
}
