// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/wolfsblu/go-chef/api"
	"github.com/wolfsblu/go-chef/domain"
	"github.com/wolfsblu/go-chef/infra/handlers"
	"github.com/wolfsblu/go-chef/infra/jobs"
	"github.com/wolfsblu/go-chef/infra/smtp"
	"github.com/wolfsblu/go-chef/infra/sqlite"
)

// Injectors from wire.go:

func InitializeAPIServer() (*api.Server, error) {
	mailer := smtp.NewSMTPMailer()
	store, err := sqlite.NewSqliteStore()
	if err != nil {
		return nil, err
	}
	recipeService := domain.NewRecipeService(mailer, store)
	recipeHandler := handlers.NewRecipeHandler(recipeService)
	securityHandler := handlers.NewSecurityHandler(recipeService)
	server, err := api.NewAPIServer(recipeHandler, securityHandler)
	if err != nil {
		return nil, err
	}
	return server, nil
}

func InitializeScheduler() (*jobs.Scheduler, error) {
	mailer := smtp.NewSMTPMailer()
	store, err := sqlite.NewSqliteStore()
	if err != nil {
		return nil, err
	}
	recipeService := domain.NewRecipeService(mailer, store)
	scheduler := jobs.NewScheduler(recipeService)
	return scheduler, nil
}

// wire.go:

var recipeServiceSet = wire.NewSet(smtp.Set, sqlite.Set, domain.NewRecipeService)
