INSERT INTO ingredients (name) VALUES
('Acorn Squash'),
('Agar-Agar'),
('Agave Nectar'),
('All-Purpose Flour'),
('Allspice'),
('Almond Butter'),
('Almond Extract'),
('Almond Flour'),
('Almonds'),
('Anchovies'),
('Apple Cider Vinegar'),
('Apples'),
('Apricots'),
('Arrowroot Powder'),
('Artichokes'),
('Arugula'),
('Asparagus'),
('Avocado Oil'),
('Avocados'),
('Baking Powder'),
('Baking Soda'),
('Balsamic Vinegar'),
('Bamboo Shoots'),
('Banana'),
('Barbecue Sauce'),
('Barley'),
('Basil'),
('Bay Leaves'),
('Beef'),
('Beer'),
('Beets'),
('Bell Peppers'),
('Bison'),
('Black Beans'),
('Black Peppercorns'),
('Black-Eyed Peas'),
('Blackberries'),
('Blueberries'),
('Boar'),
('Bok Choy'),
('Brandy'),
('Bread Flour'),
('Broccoli'),
('Broccolini'),
('Broth'),
('Brown Sugar'),
('Brussels Sprouts'),
('Buckwheat'),
('Bulgur Wheat'),
('Butter'),
('Buttermilk'),
('Butternut Squash'),
('Cabbage'),
('Cajun Seasoning'),
('Cake Flour'),
('Cannellini Beans'),
('Canola Oil'),
('Cantaloupe'),
('Capers'),
('Cardamom'),
('Cardoons'),
('Carrots'),
('Cashews'),
('Cauliflower'),
('Cayenne Pepper'),
('Celeriac'),
('Celery'),
('Celery Seed'),
('Champagne Vinegar'),
('Chanterelle Mushrooms'),
('Cheese'),
('Cherries'),
('Chia Seeds'),
('Chicken'),
('Chickpeas'),
('Chili Peppers'),
('Chili Powder'),
('Chinese Five Spice'),
('Chives'),
('Chocolate'),
('Cilantro'),
('Cinnamon'),
('Clams'),
('Cloves'),
('Cocoa Powder'),
('Coconut'),
('Coconut Cream'),
('Coconut Flour'),
('Coconut Milk'),
('Coconut Oil'),
('Cod'),
('Collard Greens'),
('Coriander Seed'),
('Corn'),
('Corn Syrup'),
('Cornish Hen'),
('Cornmeal'),
('Cornstarch'),
('Couscous'),
('Crab'),
('Cranberries'),
('Crayfish'),
('Cream'),
('Cream of Tartar'),
('Cremini Mushrooms'),
('Crème Fraîche'),
('Cucumber'),
('Cumin'),
('Currants'),
('Curry Paste'),
('Curry Powder'),
('Dates'),
('Delicata Squash'),
('Dill'),
('Distilled White Vinegar'),
('Dragon Fruit'),
('Duck'),
('Edamame'),
('Edible Flowers'),
('Eggplant'),
('Eggs'),
('Elk'),
('Endive'),
('Enoki Mushrooms'),
('Farro'),
('Fennel'),
('Fennel Seed'),
('Figs'),
('Fish Sauce'),
('Flax Seeds'),
('Galangal'),
('Garam Masala'),
('Garlic'),
('Garlic Powder'),
('Gelatin'),
('Ghee'),
('Ginger'),
('Glass Noodles'),
('Goat'),
('Gochujang'),
('Goose'),
('Gooseberries'),
('Granulated Sugar'),
('Grapefruit'),
('Grapes'),
('Grapeseed Oil'),
('Green Beans'),
('Grits'),
('Ground Coriander'),
('Ground Ginger'),
('Ground Turmeric'),
('Guava'),
('Halibut'),
('Harissa'),
('Hazelnuts'),
('Herbes de Provence'),
('Himalayan Pink Salt'),
('Hoisin Sauce'),
('Honey'),
('Honeydew'),
('Horseradish'),
('Hot Sauce'),
('Italian Seasoning'),
('Jams'),
('Jellies'),
('Jicama'),
('Kabocha Squash'),
('Kale'),
('Kasha'),
('Ketchup'),
('Kidney Beans'),
('Kiwi'),
('Kohlrabi'),
('Kombu'),
('Kosher Salt'),
('Lamb'),
('Lard'),
('Lavender'),
('Leeks'),
('Lemon Extract'),
('Lemongrass'),
('Lemons'),
('Lentils'),
('Lettuce'),
('Limes'),
('Liquid Aminos'),
('Lobster'),
('Lychees'),
('Macadamia Nuts'),
('Mackerel'),
('Mahi-Mahi'),
('Maitake Mushrooms'),
('Mangoes'),
('Maple Syrup'),
('Marjoram'),
('Mayonnaise'),
('Milk'),
('Mint'),
('Miso Paste'),
('Molasses'),
('Morel Mushrooms'),
('Mussels'),
('Mustard'),
('Mustard Greens'),
('Mustard Powder'),
('Mustard Seed'),
('Napa Cabbage'),
('Navy Beans'),
('Nectarines'),
('Nori'),
('Nutmeg'),
('Nutritional Yeast'),
('Oats'),
('Octopus'),
('Okra'),
('Olive Oil'),
('Olives'),
('Onion Powder'),
('Onions'),
('Orange Blossom Water'),
('Oranges'),
('Oregano'),
('Oyster Mushrooms'),
('Oyster Sauce'),
('Oysters'),
('Papaya'),
('Paprika'),
('Parsley'),
('Parsnips'),
('Passion Fruit'),
('Pasta'),
('Peaches'),
('Peanut Butter'),
('Peanut Oil'),
('Peanuts'),
('Pears'),
('Peas'),
('Pecans'),
('Peppermint Extract'),
('Pine Nuts'),
('Pineapple'),
('Pinto Beans'),
('Pistachios'),
('Plantain'),
('Plums'),
('Polenta'),
('Pomegranate'),
('Pomelo'),
('Poppy Seeds'),
('Porcini Mushrooms'),
('Pork'),
('Portobello Mushrooms'),
('Potatoes'),
('Powdered Sugar'),
('Pumpkin'),
('Pumpkin Seeds'),
('Quail'),
('Quince'),
('Quinoa'),
('Rabbit'),
('Radicchio'),
('Radishes'),
('Ramen Noodles'),
('Ramps'),
('Ras el Hanout'),
('Raspberries'),
('Raw Sugar'),
('Red Pepper Flakes'),
('Red Wine Vinegar'),
('Relish'),
('Rhubarb'),
('Rice'),
('Rice Flour'),
('Rice Noodles'),
('Rice Vinegar'),
('Rose Water'),
('Rosemary'),
('Rum'),
('Rutabaga'),
('Saffron'),
('Sage'),
('Salmon'),
('Sardines'),
('Scallions'),
('Scallops'),
('Sea Bass'),
('Sea Salt'),
('Seitan'),
('Semolina Flour'),
('Sesame Oil'),
('Sesame Seeds'),
('Shallots'),
('Shiitake Mushrooms'),
('Shortening'),
('Shrimp'),
('Smoked Paprika'),
('Smoked Salt'),
('Snapper'),
('Snow Peas'),
('Soba Noodles'),
('Sorrel'),
('Sour Cream'),
('Soy Sauce'),
('Soybeans'),
('Spaghetti Squash'),
('Spelt'),
('Spinach'),
('Split Peas'),
('Squid'),
('Sriracha'),
('Star Anise'),
('Starfruit'),
('Stevia'),
('Stock'),
('Strawberries'),
('Sugar Snap Peas'),
('Sunflower Oil'),
('Sunflower Seeds'),
('Sweet Potatoes'),
('Swiss Chard'),
('Table Salt'),
('Taco Seasoning'),
('Tahini'),
('Tallow'),
('Tamari'),
('Tangerines'),
('Tapioca Starch'),
('Tarragon'),
('Tempeh'),
('Teriyaki Sauce'),
('Thyme'),
('Tilapia'),
('Tofu'),
('Tomatillos'),
('Tomato Paste'),
('Tomatoes'),
('Trout'),
('Truffles'),
('Tuna'),
('Turkey'),
('Turmeric'),
('Turnips'),
('Udon Noodles'),
('Vanilla Beans'),
('Vanilla Extract'),
('Veal'),
('Vegetable Oil'),
('Venison'),
('Vodka'),
('Wakame'),
('Walnuts'),
('Wasabi'),
('Watercress'),
('Watermelon'),
('Wheat Berries'),
('Whiskey'),
('White Button Mushrooms'),
('White Wine Vinegar'),
('Whole Wheat Flour'),
('Wine'),
('Worcestershire Sauce'),
('Yams'),
('Yeast'),
('Yellow Squash'),
('Yogurt'),
('Yuzu'),
('Za''atar'),
('Zucchini');