INSERT INTO ingredients (name) VALUES
('Acorn Squash'),
('Agave Nectar'),
('All-Purpose Flour'),
('Allspice'),
('Almond'),
('Almond Butter'),
('Almond Extract'),
('Almond Flour'),
('Amaranth'),
('Anaheim Pepper'),
('Anchovy'),
('Anise Seed'),
('Annatto'),
('Apple'),
('Apple Cider Vinegar'),
('Apricot'),
('Arborio Rice'),
('Arrowroot Powder'),
('Artichoke'),
('Artichoke Heart'),
('Arugula'),
('Asafoetida'),
('Asiago Cheese'),
('Asparagus'),
('Avocado'),
('Avocado Oil'),
('Bacon'),
('Baking Powder'),
('Baking Soda'),
('Balsamic Vinegar'),
('Bamboo Shoot'),
('Banana'),
('Barbecue Sauce'),
('Barley'),
('Basmati Rice'),
('Bay Leaf'),
('Beef'),
('Beef Brisket'),
('Beef Rib'),
('Beef Roast'),
('Beef Stock'),
('Beefsteak Tomato'),
('Beer'),
('Beet'),
('Bell Pepper'),
('Bison'),
('Black Bean'),
('Black Peppercorn'),
('Black-Eyed Pea'),
('Blackberry'),
('Blue Cheese'),
('Blueberry'),
('Boar'),
('Bok Choy'),
('Bourbon'),
('Brandy'),
('Bread Flour'),
('Breadcrumb'),
('Bresaola'),
('Brie Cheese'),
('Broccoli'),
('Broccolini'),
('Brown Rice'),
('Brown Rice Syrup'),
('Brown Sugar'),
('Brussels Sprout'),
('Buckwheat'),
('Bulgur Wheat'),
('Butter'),
('Buttermilk'),
('Butternut Squash'),
('Cabbage'),
('Cajun Seasoning'),
('Cake Flour'),
('Calamari'),
('Canola Oil'),
('Cannellini Bean'),
('Cantaloupe'),
('Caper'),
('Capicola'),
('Caraway Seed'),
('Cardamom'),
('Cardoon'),
('Carrot'),
('Cashew'),
('Cauliflower'),
('Cayenne Pepper'),
('Celeriac'),
('Celery'),
('Celery Root'),
('Celery Seed'),
('Champagne Vinegar'),
('Chanterelle Mushroom'),
('Cheddar Cheese'),
('Cherry'),
('Cherry Tomato'),
('Chervil'),
('Chia Seed'),
('Chicken'),
('Chicken Breast'),
('Chicken Broth'),
('Chicken Stock'),
('Chicken Thigh'),
('Chicken Wing'),
('Chickpea'),
('Chili Pepper'),
('Chili Powder'),
('Chinese Five Spice'),
('Chive'),
('Chocolate'),
('Chocolate Chip'),
('Chorizo'),
('Cilantro'),
('Cinnamon'),
('Clam'),
('Clove'),
('Cocoa Powder'),
('Coconut'),
('Coconut Aminos'),
('Coconut Cream'),
('Coconut Flour'),
('Coconut Milk'),
('Coconut Oil'),
('Coconut Sugar'),
('Cod'),
('Colby Cheese'),
('Collard Green'),
('Coriander'),
('Corn'),
('Corn Syrup'),
('Cornish Hen'),
('Cornmeal'),
('Cornstarch'),
('Cottage Cheese'),
('Courgette'),
('Couscous'),
('Crab'),
('Cranberry'),
('Crayfish'),
('Cream'),
('Cream Cheese'),
('Cream of Tartar'),
('Crème Fraîche'),
('Cremini Mushroom'),
('Crouton'),
('Cucumber'),
('Cumin'),
('Currant'),
('Curry Leaf'),
('Curry Paste'),
('Curry Powder'),
('Daikon Radish'),
('Dark Chocolate'),
('Date'),
('Date Syrup'),
('Delicata Squash'),
('Dijon Mustard'),
('Dill'),
('Distilled White Vinegar'),
('Dragon Fruit'),
('Duck'),
('Duck Fat'),
('Edamame'),
('Edible Flower'),
('Egg'),
('Eggplant'),
('Elk'),
('Endive'),
('Enoki Mushroom'),
('Extra Virgin Olive Oil'),
('Farfalle'),
('Farro'),
('Fennel'),
('Fennel Seed'),
('Fenugreek'),
('Feta Cheese'),
('Fig'),
('Fingerling Potato'),
('Fish Sauce'),
('Fish Stock'),
('Flank Steak'),
('Flax Seed'),
('Flour'),
('Frisée'),
('Fusilli'),
('Galangal'),
('Garam Masala'),
('Garlic'),
('Garlic Powder'),
('Gelatin'),
('Ghee'),
('Ginger'),
('Glass Noodle'),
('Goat'),
('Goat Cheese'),
('Gochujang'),
('Golden Syrup'),
('Goose'),
('Gooseberry'),
('Gorgonzola Cheese'),
('Gouda Cheese'),
('Grape'),
('Grape Tomato'),
('Grapefruit'),
('Grapeseed Oil'),
('Green Bean'),
('Green Bell Pepper'),
('Green Onion'),
('Grits'),
('Ground Beef'),
('Ground Lamb'),
('Ground Pork'),
('Ground Turkey'),
('Guanciale'),
('Guava'),
('Habanero Pepper'),
('Halibut'),
('Halloumi Cheese'),
('Ham'),
('Harissa'),
('Hazelnut'),
('Heavy Cream'),
('Heirloom Tomato'),
('Herbes de Provence'),
('Himalayan Pink Salt'),
('Hoisin Sauce'),
('Honey'),
('Honeydew'),
('Horseradish'),
('Hot Paprika'),
('Hot Sauce'),
('Iceberg Lettuce'),
('Italian Seasoning'),
('Jalapeño Pepper'),
('Jam'),
('Jasmine Rice'),
('Jelly'),
('Jicama'),
('Juniper Berry'),
('Kabocha Squash'),
('Kalamata Olive'),
('Kale'),
('Ketchup'),
('Kidney Bean'),
('Kimchi'),
('Kiwi'),
('Kohlrabi'),
('Kombu'),
('Kosher Salt'),
('Lamb'),
('Lard'),
('Lasagna Noodle'),
('Lavender'),
('Leek'),
('Lemon'),
('Lemon Extract'),
('Lemon Juice'),
('Lemon Zest'),
('Lemongrass'),
('Lentil'),
('Lettuce'),
('Lime'),
('Lime Juice'),
('Lime Zest'),
('Linguine'),
('Liquid Aminos'),
('Lobster'),
('Lovage'),
('Lychee'),
('Macadamia Nut'),
('Macaroni'),
('Mace'),
('Mackerel'),
('Mahi-Mahi'),
('Maitake Mushroom'),
('Mango'),
('Maple Syrup'),
('Marjoram'),
('Mascarpone Cheese'),
('Mayonnaise'),
('Milk'),
('Milk Chocolate'),
('Millet'),
('Mint'),
('Mirin'),
('Miso Paste'),
('Molasses'),
('Monterey Jack Cheese'),
('Morel Mushroom'),
('Mortadella'),
('Mozzarella Cheese'),
('Mushroom'),
('Mussel'),
('Mustard'),
('Mustard Green'),
('Mustard Powder'),
('Mustard Seed'),
('Napa Cabbage'),
('Navy Bean'),
('Nectarine'),
('Nori'),
('Nutmeg'),
('Nutritional Yeast'),
('Oat'),
('Octopus'),
('Okra'),
('Olive'),
('Olive Oil'),
('Onion'),
('Onion Powder'),
('Orange'),
('Orange Blossom Water'),
('Orange Juice'),
('Orange Zest'),
('Orecchiette'),
('Oregano'),
('Oyster'),
('Oyster Mushroom'),
('Oyster Sauce'),
('Pancetta'),
('Panko Breadcrumb'),
('Pappardelle'),
('Papaya'),
('Paprika'),
('Parmesan Cheese'),
('Parsley'),
('Parsnip'),
('Passion Fruit'),
('Pasta'),
('Pea'),
('Peach'),
('Peanut'),
('Peanut Butter'),
('Peanut Oil'),
('Pear'),
('Pecan'),
('Pecorino Romano Cheese'),
('Penne'),
('Peppermint Extract'),
('Pepperoni'),
('Persimmon'),
('Pesto'),
('Phyllo Dough'),
('Pickled Ginger'),
('Pickled Onion'),
('Pine Nut'),
('Pineapple'),
('Pinto Bean'),
('Pistachio'),
('Plantain'),
('Plum'),
('Poblano Pepper'),
('Polenta'),
('Pomegranate'),
('Pomelo'),
('Poppy Seed'),
('Porcini Mushroom'),
('Pork'),
('Pork Belly'),
('Pork Chop'),
('Pork Rib'),
('Pork Tenderloin'),
('Portobello Mushroom'),
('Potato'),
('Potato Starch'),
('Powdered Sugar'),
('Prosciutto'),
('Provolone Cheese'),
('Puff Pastry'),
('Pumpkin'),
('Pumpkin Seed'),
('Quail'),
('Quince'),
('Quinoa'),
('Rabbit'),
('Radicchio'),
('Radish'),
('Raisin'),
('Ramen Noodle'),
('Ramp'),
('Ras el Hanout'),
('Raspberry'),
('Raw Sugar'),
('Red Bell Pepper'),
('Red Lentil'),
('Red Onion'),
('Red Pepper Flake'),
('Red Potato'),
('Red Wine'),
('Red Wine Vinegar'),
('Relish'),
('Rhubarb'),
('Rice'),
('Rice Flour'),
('Rice Noodle'),
('Rice Paper'),
('Rice Vinegar'),
('Ricotta Cheese'),
('Rigatoni'),
('Roma Tomato'),
('Romaine Lettuce'),
('Rose Water'),
('Rosemary'),
('Rum'),
('Russet Potato'),
('Rutabaga'),
('Rye Flour'),
('Saffron'),
('Sage'),
('Sake'),
('Salami'),
('Salmon'),
('Salt'),
('Sardine'),
('Sauerkraut'),
('Sausage'),
('Scallion'),
('Scallop'),
('Schmaltz'),
('Sea Salt'),
('Seaweed'),
('Seitan'),
('Semolina Flour'),
('Serrano Pepper'),
('Sesame Oil'),
('Sesame Seed'),
('Shallot'),
('Sherry'),
('Sherry Vinegar'),
('Shiitake Mushroom'),
('Shortening'),
('Shrimp'),
('Sirloin Steak'),
('Smoked Paprika'),
('Smoked Salt'),
('Snapper'),
('Snow Pea'),
('Soba Noodle'),
('Sorrel'),
('Sorghum'),
('Sour Cream'),
('Soy Sauce'),
('Soybean'),
('Spaghetti'),
('Spaghetti Squash'),
('Spelt'),
('Spinach'),
('Split Pea'),
('Sriracha'),
('Star Anise'),
('Starfruit'),
('Steak'),
('Stevia'),
('Stock'),
('Strawberry'),
('Sugar'),
('Sugar Snap Pea'),
('Sumac'),
('Sun-Dried Tomato'),
('Sunflower Oil'),
('Sunflower Seed'),
('Sweet Paprika'),
('Sweet Potato'),
('Swiss Chard'),
('Swiss Cheese'),
('Swordfish'),
('Tabasco Sauce'),
('Table Salt'),
('Taco Seasoning'),
('Tahini'),
('Tallow'),
('Tamari'),
('Tamarind'),
('Tangerine'),
('Tapioca Starch'),
('Tarragon'),
('Tempeh'),
('Teriyaki Sauce'),
('Thyme'),
('Tilapia'),
('Tofu'),
('Tomatillo'),
('Tomato'),
('Tomato Paste'),
('Trout'),
('Truffle'),
('Tuna'),
('Turbinado Sugar'),
('Turkey'),
('Turmeric'),
('Turnip'),
('Udon Noodle'),
('Vanilla Bean'),
('Vanilla Extract'),
('Veal'),
('Vegetable Broth'),
('Vegetable Oil'),
('Venison'),
('Vermouth'),
('Vinegar'),
('Vodka'),
('Wakame'),
('Walnut'),
('Walnut Oil'),
('Wasabi'),
('Watercress'),
('Watermelon'),
('Wheat Berry'),
('Whipping Cream'),
('White Chocolate'),
('White Onion'),
('White Rice'),
('White Wine'),
('White Wine Vinegar'),
('Whole Wheat Flour'),
('Wild Rice'),
('Wine'),
('Worcestershire Sauce'),
('Yam'),
('Yeast'),
('Yellow Bell Pepper'),
('Yellow Onion'),
('Yellow Squash'),
('Yogurt'),
('Yukon Gold Potato'),
('Yuzu'),
('Za''atar'),
('Zucchini');