INSERT INTO ingredients (name) VALUES
('Acorn Squash'),
('Agave Nectar'),
('All-Purpose Flour'),
('Allspice'),
('Almond'),
('Almond Butter'),
('Almond Extract'),
('Almond Flour'),
('Anaheim Pepper'),
('Anchovy'),
('Apple'),
('Apple Cider Vinegar'),
('Apricot'),
('Arborio Rice'),
('Arrowroot Powder'),
('Artichoke'),
('Arugula'),
('Asafoetida'),
('Asparagus'),
('Avocado'),
('Avocado Oil'),
('Bacon'),
('Baking Powder'),
('Baking Soda'),
('Balsamic Vinegar'),
('Bamboo Shoot'),
('Banana'),
('Barbecue Sauce'),
('Barley'),
('Basmati Rice'),
('Bay Leaf'),
('Beef'),
('Beef Brisket'),
('Beef Rib'),
('Beef Roast'),
('Beefsteak Tomato'),
('Beer'),
('Beet'),
('Bell Pepper'),
('Bison'),
('Black Bean'),
('Black Peppercorn'),
('Black-Eyed Pea'),
('Blackberry'),
('Blue Cheese'),
('Blueberry'),
('Boar'),
('Bok Choy'),
('Bourbon'),
('Brandy'),
('Bread Flour'),
('Brie Cheese'),
('Broccoli'),
('Broccolini'),
('Brown Rice'),
('Brown Sugar'),
('Brussels Sprout'),
('Buckwheat'),
('Bulgur Wheat'),
('Butter'),
('Buttermilk'),
('Butternut Squash'),
('Cabbage'),
('Cajun Seasoning'),
('Cake Flour'),
('Canola Oil'),
('Cannellini Bean'),
('Cantaloupe'),
('Caper'),
('Caraway Seed'),
('Cardamom'),
('Cardoon'),
('Carrot'),
('Cashew'),
('Cauliflower'),
('Cayenne Pepper'),
('Celeriac'),
('Celery'),
('Celery Seed'),
('Champagne Vinegar'),
('Chanterelle Mushroom'),
('Cheddar Cheese'),
('Cherry'),
('Cherry Tomato'),
('Chervil'),
('Chia Seed'),
('Chicken'),
('Chicken Breast'),
('Chicken Broth'),
('Chicken Stock'),
('Chicken Thigh'),
('Chicken Wing'),
('Chickpea'),
('Chili Pepper'),
('Chili Powder'),
('Chinese Five Spice'),
('Chive'),
('Chocolate'),
('Chocolate Chip'),
('Chorizo'),
('Cilantro'),
('Cinnamon'),
('Clam'),
('Clove'),
('Cocoa Powder'),
('Coconut'),
('Coconut Cream'),
('Coconut Flour'),
('Coconut Milk'),
('Coconut Oil'),
('Cod'),
('Collard Green'),
('Coriander'),
('Corn'),
('Corn Syrup'),
('Cornish Hen'),
('Cornmeal'),
('Cornstarch'),
('Cottage Cheese'),
('Courgette'),
('Couscous'),
('Crab'),
('Cranberry'),
('Crayfish'),
('Cream'),
('Cream Cheese'),
('Cream of Tartar'),
('Crème Fraîche'),
('Cremini Mushroom'),
('Cucumber'),
('Cumin'),
('Currant'),
('Curry Leaf'),
('Curry Paste'),
('Curry Powder'),
('Daikon Radish'),
('Dark Chocolate'),
('Date'),
('Delicata Squash'),
('Dijon Mustard'),
('Dill'),
('Distilled White Vinegar'),
('Dragon Fruit'),
('Duck'),
('Edamame'),
('Egg'),
('Eggplant'),
('Elk'),
('Endive'),
('Enoki Mushroom'),
('Extra Virgin Olive Oil'),
('Farro'),
('Fennel'),
('Fennel Seed'),
('Fenugreek'),
('Feta Cheese'),
('Fig'),
('Fingerling Potato'),
('Fish Sauce'),
('Flank Steak'),
('Flax Seed'),
('Flour'),
('Frisée'),
('Galangal'),
('Garam Masala'),
('Garlic'),
('Garlic Powder'),
('Gelatin'),
('Ghee'),
('Ginger'),
('Glass Noodle'),
('Goat'),
('Goat Cheese'),
('Gochujang'),
('Goose'),
('Gooseberry'),
('Gouda Cheese'),
('Grape'),
('Grape Tomato'),
('Grapefruit'),
('Grapeseed Oil'),
('Green Bean'),
('Green Bell Pepper'),
('Green Onion'),
('Grits'),
('Ground Beef'),
('Ground Lamb'),
('Ground Pork'),
('Ground Turkey'),
('Guava'),
('Habanero Pepper'),
('Halibut'),
('Ham'),
('Harissa'),
('Hazelnut'),
('Heavy Cream'),
('Heirloom Tomato'),
('Herbes de Provence'),
('Himalayan Pink Salt'),
('Hoisin Sauce'),
('Honey'),
('Honeydew'),
('Horseradish'),
('Hot Paprika'),
('Hot Sauce'),
('Iceberg Lettuce'),
('Italian Seasoning'),
('Jalapeño Pepper'),
('Jam'),
('Jasmine Rice'),
('Jelly'),
('Jicama'),
('Kabocha Squash'),
('Kale'),
('Ketchup'),
('Kidney Bean'),
('Kiwi'),
('Kohlrabi'),
('Kombu'),
('Kosher Salt'),
('Lamb'),
('Lard'),
('Lavender'),
('Leek'),
('Lemon'),
('Lemon Extract'),
('Lemongrass'),
('Lentil'),
('Lettuce'),
('Lime'),
('Liquid Aminos'),
('Lobster'),
('Lychee'),
('Macadamia Nut'),
('Mackerel'),
('Mahi-Mahi'),
('Maitake Mushroom'),
('Mango'),
('Maple Syrup'),
('Marjoram'),
('Mayonnaise'),
('Milk'),
('Milk Chocolate'),
('Mint'),
('Miso Paste'),
('Molasses'),
('Morel Mushroom'),
('Mozzarella Cheese'),
('Mushroom'),
('Mussel'),
('Mustard'),
('Mustard Green'),
('Mustard Powder'),
('Mustard Seed'),
('Napa Cabbage'),
('Navy Bean'),
('Nectarine'),
('Nori'),
('Nutmeg'),
('Nutritional Yeast'),
('Oat'),
('Octopus'),
('Okra'),
('Olive'),
('Olive Oil'),
('Onion'),
('Onion Powder'),
('Orange'),
('Orange Blossom Water'),
('Oregano'),
('Oyster'),
('Oyster Mushroom'),
('Oyster Sauce'),
('Papaya'),
('Paprika'),
('Parmesan Cheese'),
('Parsley'),
('Parsnip'),
('Passion Fruit'),
('Pasta'),
('Pea'),
('Peach'),
('Peanut'),
('Peanut Butter'),
('Peanut Oil'),
('Pear'),
('Pecan'),
('Penne'),
('Peppermint Extract'),
('Pepperoni'),
('Pesto'),
('Pine Nut'),
('Pineapple'),
('Pinto Bean'),
('Pistachio'),
('Plantain'),
('Plum'),
('Poblano Pepper'),
('Polenta'),
('Pomegranate'),
('Pomelo'),
('Poppy Seed'),
('Porcini Mushroom'),
('Pork'),
('Pork Belly'),
('Pork Chop'),
('Pork Rib'),
('Pork Tenderloin'),
('Portobello Mushroom'),
('Potato'),
('Powdered Sugar'),
('Prosciutto'),
('Provolone Cheese'),
('Pumpkin'),
('Pumpkin Seed'),
('Quail'),
('Quince'),
('Quinoa'),
('Rabbit'),
('Radicchio'),
('Radish'),
('Raisin'),
('Ramen Noodle'),
('Ramp'),
('Ras el Hanout'),
('Raspberry'),
('Raw Sugar'),
('Red Bell Pepper'),
('Red Lentil'),
('Red Onion'),
('Red Pepper Flake'),
('Red Potato'),
('Red Wine'),
('Red Wine Vinegar'),
('Relish'),
('Rhubarb'),
('Rice'),
('Rice Flour'),
('Rice Noodle'),
('Rice Paper'),
('Rice Vinegar'),
('Ricotta Cheese'),
('Roma Tomato'),
('Romaine Lettuce'),
('Rose Water'),
('Rosemary'),
('Rum'),
('Russet Potato'),
('Rutabaga'),
('Saffron'),
('Sage'),
('Salami'),
('Salmon'),
('Salt'),
('Sardine'),
('Sausage'),
('Scallion'),
('Scallop'),
('Sea Salt'),
('Seaweed'),
('Seitan'),
('Semolina Flour'),
('Serrano Pepper'),
('Sesame Oil'),
('Sesame Seed'),
('Shallot'),
('Shiitake Mushroom'),
('Shortening'),
('Shrimp'),
('Sirloin Steak'),
('Smoked Paprika'),
('Smoked Salt'),
('Snapper'),
('Snow Pea'),
('Soba Noodle'),
('Sorrel'),
('Sour Cream'),
('Soy Sauce'),
('Soybean'),
('Spaghetti'),
('Spaghetti Squash'),
('Spelt'),
('Spinach'),
('Split Pea'),
('Sriracha'),
('Star Anise'),
('Starfruit'),
('Steak'),
('Stevia'),
('Stock'),
('Strawberry'),
('Sugar'),
('Sugar Snap Pea'),
('Sumac'),
('Sunflower Oil'),
('Sunflower Seed'),
('Sweet Paprika'),
('Sweet Potato'),
('Swiss Chard'),
('Swiss Cheese'),
('Swordfish'),
('Tabasco Sauce'),
('Table Salt'),
('Taco Seasoning'),
('Tahini'),
('Tallow'),
('Tamari'),
('Tamarind'),
('Tangerine'),
('Tapioca Starch'),
('Tarragon'),
('Tempeh'),
('Teriyaki Sauce'),
('Thyme'),
('Tilapia'),
('Tofu'),
('Tomatillo'),
('Tomato'),
('Tomato Paste'),
('Trout'),
('Truffle'),
('Tuna'),
('Turbinado Sugar'),
('Turkey'),
('Turmeric'),
('Turnip'),
('Udon Noodle'),
('Vanilla Bean'),
('Vanilla Extract'),
('Veal'),
('Vegetable Broth'),
('Vegetable Oil'),
('Venison'),
('Vinegar'),
('Vodka'),
('Wakame'),
('Walnut'),
('Wasabi'),
('Watercress'),
('Watermelon'),
('Wheat Berry'),
('Whipping Cream'),
('White Chocolate'),
('White Onion'),
('White Rice'),
('White Wine'),
('White Wine Vinegar'),
('Whole Wheat Flour'),
('Wild Rice'),
('Wine'),
('Worcestershire Sauce'),
('Yam'),
('Yeast'),
('Yellow Bell Pepper'),
('Yellow Onion'),
('Yellow Squash'),
('Yogurt'),
('Yukon Gold Potato'),
('Yuzu'),
('Za''atar'),
('Zucchini');