-- Insert common recipe tags

-- Dietary & Lifestyle Tags
INSERT OR IGNORE INTO tags (name) VALUES
    ('Vegetarian'),
    ('Vegan'),
    ('Gluten-Free'),
    ('Dairy-Free'),
    ('Keto'),
    ('Low-Carb'),
    ('Paleo'),
    ('Sugar-Free'),
    ('Nut-Free'),
    ('Soy-Free'),
    ('Egg-Free'),
    ('Lactose-Free'),
    ('High-Protein'),
    ('Low-Sodium'),
    ('Heart-Healthy'),
    ('Diabetic-Friendly'),
    ('Weight-Loss'),
    ('Whole30'),
    ('Raw');

-- Meal Types
INSERT OR IGNORE INTO tags (name) VALUES
    ('Breakfast'),
    ('Lunch'),
    ('Dinner'),
    ('Brunch'),
    ('Snack'),
    ('Dessert'),
    ('Appetizer'),
    ('Side-Dish'),
    ('Main-Course'),
    ('Salad'),
    ('Soup'),
    ('Beverage'),
    ('Smoothie'),
    ('Cocktail');

-- Cooking Methods
INSERT OR IGNORE INTO tags (name) VALUES
    ('Baked'),
    ('Grilled'),
    ('Fried'),
    ('Roasted'),
    ('Steamed'),
    ('Sautéed'),
    ('Slow-Cooker'),
    ('Instant-Pot'),
    ('Air-Fryer'),
    ('No-Bake'),
    ('One-Pot'),
    ('Sheet-Pan'),
    ('Stir-Fry'),
    ('Pressure-Cooker'),
    ('Microwave'),
    ('Braised'),
    ('Poached'),
    ('Smoked');

-- Cuisine Types
INSERT OR IGNORE INTO tags (name) VALUES
    ('Italian'),
    ('Mexican'),
    ('Asian'),
    ('Indian'),
    ('Thai'),
    ('Chinese'),
    ('Japanese'),
    ('Korean'),
    ('French'),
    ('Greek'),
    ('Spanish'),
    ('Mediterranean'),
    ('Middle-Eastern'),
    ('American'),
    ('Southern'),
    ('Tex-Mex'),
    ('Caribbean'),
    ('German'),
    ('British'),
    ('Moroccan'),
    ('Vietnamese'),
    ('Lebanese'),
    ('Turkish'),
    ('Brazilian'),
    ('Ethiopian');

-- Time & Difficulty
INSERT OR IGNORE INTO tags (name) VALUES
    ('Quick'),
    ('15-Minutes'),
    ('30-Minutes'),
    ('Make-Ahead'),
    ('Freezer-Friendly'),
    ('Meal-Prep'),
    ('Easy'),
    ('Beginner'),
    ('Intermediate'),
    ('Advanced'),
    ('Weekend-Project');

-- Occasions & Seasons
INSERT OR IGNORE INTO tags (name) VALUES
    ('Holiday'),
    ('Christmas'),
    ('Thanksgiving'),
    ('Easter'),
    ('Halloween'),
    ('Birthday'),
    ('Party'),
    ('Date-Night'),
    ('Family-Friendly'),
    ('Kid-Friendly'),
    ('Game-Day'),
    ('Summer'),
    ('Fall'),
    ('Winter'),
    ('Spring'),
    ('BBQ'),
    ('Picnic'),
    ('Potluck'),
    ('Brunch-Party');

-- Ingredients & Features
INSERT OR IGNORE INTO tags (name) VALUES
    ('Chocolate'),
    ('Spicy'),
    ('Sweet'),
    ('Savory'),
    ('Creamy'),
    ('Crispy'),
    ('Cheesy'),
    ('Fresh'),
    ('Comfort-Food'),
    ('Healthy'),
    ('Indulgent'),
    ('Light'),
    ('Rich'),
    ('Tangy'),
    ('Smoky'),
    ('Herb-Crusted'),
    ('Garlic'),
    ('Lemon'),
    ('Coconut'),
    ('Avocado'),
    ('Seasonal'),
    ('Local'),
    ('Organic'),
    ('Budget-Friendly'),
    ('Elegant'),
    ('Rustic'),
    ('Gourmet'),
    ('Classic'),
    ('Modern'),
    ('Fusion');