//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Ingredients = newIngredientsTable("", "ingredients", "")

type ingredientsTable struct {
	sqlite.Table

	// Columns
	ID   sqlite.ColumnInteger
	Name sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type IngredientsTable struct {
	ingredientsTable

	EXCLUDED ingredientsTable
}

// AS creates new IngredientsTable with assigned alias
func (a IngredientsTable) AS(alias string) *IngredientsTable {
	return newIngredientsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new IngredientsTable with assigned schema name
func (a IngredientsTable) FromSchema(schemaName string) *IngredientsTable {
	return newIngredientsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new IngredientsTable with assigned table prefix
func (a IngredientsTable) WithPrefix(prefix string) *IngredientsTable {
	return newIngredientsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new IngredientsTable with assigned table suffix
func (a IngredientsTable) WithSuffix(suffix string) *IngredientsTable {
	return newIngredientsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newIngredientsTable(schemaName, tableName, alias string) *IngredientsTable {
	return &IngredientsTable{
		ingredientsTable: newIngredientsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newIngredientsTableImpl("", "excluded", ""),
	}
}

func newIngredientsTableImpl(schemaName, tableName, alias string) ingredientsTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		NameColumn     = sqlite.StringColumn("name")
		allColumns     = sqlite.ColumnList{IDColumn, NameColumn}
		mutableColumns = sqlite.ColumnList{NameColumn}
		defaultColumns = sqlite.ColumnList{}
	)

	return ingredientsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Name: NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
