//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var IngredientNutrients = newIngredientNutrientsTable("", "ingredient_nutrients", "")

type ingredientNutrientsTable struct {
	sqlite.Table

	// Columns
	IngredientID sqlite.ColumnInteger
	NutrientID   sqlite.ColumnInteger
	Amount       sqlite.ColumnFloat

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type IngredientNutrientsTable struct {
	ingredientNutrientsTable

	EXCLUDED ingredientNutrientsTable
}

// AS creates new IngredientNutrientsTable with assigned alias
func (a IngredientNutrientsTable) AS(alias string) *IngredientNutrientsTable {
	return newIngredientNutrientsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new IngredientNutrientsTable with assigned schema name
func (a IngredientNutrientsTable) FromSchema(schemaName string) *IngredientNutrientsTable {
	return newIngredientNutrientsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new IngredientNutrientsTable with assigned table prefix
func (a IngredientNutrientsTable) WithPrefix(prefix string) *IngredientNutrientsTable {
	return newIngredientNutrientsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new IngredientNutrientsTable with assigned table suffix
func (a IngredientNutrientsTable) WithSuffix(suffix string) *IngredientNutrientsTable {
	return newIngredientNutrientsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newIngredientNutrientsTable(schemaName, tableName, alias string) *IngredientNutrientsTable {
	return &IngredientNutrientsTable{
		ingredientNutrientsTable: newIngredientNutrientsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                 newIngredientNutrientsTableImpl("", "excluded", ""),
	}
}

func newIngredientNutrientsTableImpl(schemaName, tableName, alias string) ingredientNutrientsTable {
	var (
		IngredientIDColumn = sqlite.IntegerColumn("ingredient_id")
		NutrientIDColumn   = sqlite.IntegerColumn("nutrient_id")
		AmountColumn       = sqlite.FloatColumn("amount")
		allColumns         = sqlite.ColumnList{IngredientIDColumn, NutrientIDColumn, AmountColumn}
		mutableColumns     = sqlite.ColumnList{AmountColumn}
		defaultColumns     = sqlite.ColumnList{}
	)

	return ingredientNutrientsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		IngredientID: IngredientIDColumn,
		NutrientID:   NutrientIDColumn,
		Amount:       AmountColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
