//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var MealPlan = newMealPlanTable("", "meal_plan", "")

type mealPlanTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnInteger
	Date      sqlite.ColumnString
	UserID    sqlite.ColumnInteger
	RecipeID  sqlite.ColumnInteger
	SortOrder sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type MealPlanTable struct {
	mealPlanTable

	EXCLUDED mealPlanTable
}

// AS creates new MealPlanTable with assigned alias
func (a MealPlanTable) AS(alias string) *MealPlanTable {
	return newMealPlanTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MealPlanTable with assigned schema name
func (a MealPlanTable) FromSchema(schemaName string) *MealPlanTable {
	return newMealPlanTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MealPlanTable with assigned table prefix
func (a MealPlanTable) WithPrefix(prefix string) *MealPlanTable {
	return newMealPlanTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MealPlanTable with assigned table suffix
func (a MealPlanTable) WithSuffix(suffix string) *MealPlanTable {
	return newMealPlanTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMealPlanTable(schemaName, tableName, alias string) *MealPlanTable {
	return &MealPlanTable{
		mealPlanTable: newMealPlanTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newMealPlanTableImpl("", "excluded", ""),
	}
}

func newMealPlanTableImpl(schemaName, tableName, alias string) mealPlanTable {
	var (
		IDColumn        = sqlite.IntegerColumn("id")
		DateColumn      = sqlite.StringColumn("date")
		UserIDColumn    = sqlite.IntegerColumn("user_id")
		RecipeIDColumn  = sqlite.IntegerColumn("recipe_id")
		SortOrderColumn = sqlite.IntegerColumn("sort_order")
		allColumns      = sqlite.ColumnList{IDColumn, DateColumn, UserIDColumn, RecipeIDColumn, SortOrderColumn}
		mutableColumns  = sqlite.ColumnList{DateColumn, UserIDColumn, RecipeIDColumn, SortOrderColumn}
		defaultColumns  = sqlite.ColumnList{DateColumn, SortOrderColumn}
	)

	return mealPlanTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		Date:      DateColumn,
		UserID:    UserIDColumn,
		RecipeID:  RecipeIDColumn,
		SortOrder: SortOrderColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
