//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Nutrients = newNutrientsTable("", "nutrients", "")

type nutrientsTable struct {
	sqlite.Table

	// Columns
	ID   sqlite.ColumnInteger
	Name sqlite.ColumnString
	Unit sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type NutrientsTable struct {
	nutrientsTable

	EXCLUDED nutrientsTable
}

// AS creates new NutrientsTable with assigned alias
func (a NutrientsTable) AS(alias string) *NutrientsTable {
	return newNutrientsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new NutrientsTable with assigned schema name
func (a NutrientsTable) FromSchema(schemaName string) *NutrientsTable {
	return newNutrientsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new NutrientsTable with assigned table prefix
func (a NutrientsTable) WithPrefix(prefix string) *NutrientsTable {
	return newNutrientsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new NutrientsTable with assigned table suffix
func (a NutrientsTable) WithSuffix(suffix string) *NutrientsTable {
	return newNutrientsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newNutrientsTable(schemaName, tableName, alias string) *NutrientsTable {
	return &NutrientsTable{
		nutrientsTable: newNutrientsTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newNutrientsTableImpl("", "excluded", ""),
	}
}

func newNutrientsTableImpl(schemaName, tableName, alias string) nutrientsTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		NameColumn     = sqlite.StringColumn("name")
		UnitColumn     = sqlite.StringColumn("unit")
		allColumns     = sqlite.ColumnList{IDColumn, NameColumn, UnitColumn}
		mutableColumns = sqlite.ColumnList{NameColumn, UnitColumn}
		defaultColumns = sqlite.ColumnList{}
	)

	return nutrientsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Name: NameColumn,
		Unit: UnitColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
