//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var PasswordResets = newPasswordResetsTable("", "password_resets", "")

type passwordResetsTable struct {
	sqlite.Table

	// Columns
	UserID    sqlite.ColumnInteger
	Token     sqlite.ColumnString
	CreatedAt sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type PasswordResetsTable struct {
	passwordResetsTable

	EXCLUDED passwordResetsTable
}

// AS creates new PasswordResetsTable with assigned alias
func (a PasswordResetsTable) AS(alias string) *PasswordResetsTable {
	return newPasswordResetsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PasswordResetsTable with assigned schema name
func (a PasswordResetsTable) FromSchema(schemaName string) *PasswordResetsTable {
	return newPasswordResetsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PasswordResetsTable with assigned table prefix
func (a PasswordResetsTable) WithPrefix(prefix string) *PasswordResetsTable {
	return newPasswordResetsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PasswordResetsTable with assigned table suffix
func (a PasswordResetsTable) WithSuffix(suffix string) *PasswordResetsTable {
	return newPasswordResetsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPasswordResetsTable(schemaName, tableName, alias string) *PasswordResetsTable {
	return &PasswordResetsTable{
		passwordResetsTable: newPasswordResetsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newPasswordResetsTableImpl("", "excluded", ""),
	}
}

func newPasswordResetsTableImpl(schemaName, tableName, alias string) passwordResetsTable {
	var (
		UserIDColumn    = sqlite.IntegerColumn("user_id")
		TokenColumn     = sqlite.StringColumn("token")
		CreatedAtColumn = sqlite.TimestampColumn("created_at")
		allColumns      = sqlite.ColumnList{UserIDColumn, TokenColumn, CreatedAtColumn}
		mutableColumns  = sqlite.ColumnList{TokenColumn, CreatedAtColumn}
		defaultColumns  = sqlite.ColumnList{CreatedAtColumn}
	)

	return passwordResetsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:    UserIDColumn,
		Token:     TokenColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
