//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var RecipeImages = newRecipeImagesTable("", "recipe_images", "")

type recipeImagesTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnInteger
	RecipeID  sqlite.ColumnInteger
	Path      sqlite.ColumnString
	SortOrder sqlite.ColumnInteger
	CreatedAt sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type RecipeImagesTable struct {
	recipeImagesTable

	EXCLUDED recipeImagesTable
}

// AS creates new RecipeImagesTable with assigned alias
func (a RecipeImagesTable) AS(alias string) *RecipeImagesTable {
	return newRecipeImagesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RecipeImagesTable with assigned schema name
func (a RecipeImagesTable) FromSchema(schemaName string) *RecipeImagesTable {
	return newRecipeImagesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RecipeImagesTable with assigned table prefix
func (a RecipeImagesTable) WithPrefix(prefix string) *RecipeImagesTable {
	return newRecipeImagesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RecipeImagesTable with assigned table suffix
func (a RecipeImagesTable) WithSuffix(suffix string) *RecipeImagesTable {
	return newRecipeImagesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRecipeImagesTable(schemaName, tableName, alias string) *RecipeImagesTable {
	return &RecipeImagesTable{
		recipeImagesTable: newRecipeImagesTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newRecipeImagesTableImpl("", "excluded", ""),
	}
}

func newRecipeImagesTableImpl(schemaName, tableName, alias string) recipeImagesTable {
	var (
		IDColumn        = sqlite.IntegerColumn("id")
		RecipeIDColumn  = sqlite.IntegerColumn("recipe_id")
		PathColumn      = sqlite.StringColumn("path")
		SortOrderColumn = sqlite.IntegerColumn("sort_order")
		CreatedAtColumn = sqlite.TimestampColumn("created_at")
		allColumns      = sqlite.ColumnList{IDColumn, RecipeIDColumn, PathColumn, SortOrderColumn, CreatedAtColumn}
		mutableColumns  = sqlite.ColumnList{RecipeIDColumn, PathColumn, SortOrderColumn, CreatedAtColumn}
		defaultColumns  = sqlite.ColumnList{CreatedAtColumn}
	)

	return recipeImagesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		RecipeID:  RecipeIDColumn,
		Path:      PathColumn,
		SortOrder: SortOrderColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
