//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var RecipeIngredients = newRecipeIngredientsTable("", "recipe_ingredients", "")

type recipeIngredientsTable struct {
	sqlite.Table

	// Columns
	ID           sqlite.ColumnInteger
	StepID       sqlite.ColumnInteger
	IngredientID sqlite.ColumnInteger
	UnitID       sqlite.ColumnInteger
	Amount       sqlite.ColumnFloat
	SortOrder    sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type RecipeIngredientsTable struct {
	recipeIngredientsTable

	EXCLUDED recipeIngredientsTable
}

// AS creates new RecipeIngredientsTable with assigned alias
func (a RecipeIngredientsTable) AS(alias string) *RecipeIngredientsTable {
	return newRecipeIngredientsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RecipeIngredientsTable with assigned schema name
func (a RecipeIngredientsTable) FromSchema(schemaName string) *RecipeIngredientsTable {
	return newRecipeIngredientsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RecipeIngredientsTable with assigned table prefix
func (a RecipeIngredientsTable) WithPrefix(prefix string) *RecipeIngredientsTable {
	return newRecipeIngredientsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RecipeIngredientsTable with assigned table suffix
func (a RecipeIngredientsTable) WithSuffix(suffix string) *RecipeIngredientsTable {
	return newRecipeIngredientsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRecipeIngredientsTable(schemaName, tableName, alias string) *RecipeIngredientsTable {
	return &RecipeIngredientsTable{
		recipeIngredientsTable: newRecipeIngredientsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newRecipeIngredientsTableImpl("", "excluded", ""),
	}
}

func newRecipeIngredientsTableImpl(schemaName, tableName, alias string) recipeIngredientsTable {
	var (
		IDColumn           = sqlite.IntegerColumn("id")
		StepIDColumn       = sqlite.IntegerColumn("step_id")
		IngredientIDColumn = sqlite.IntegerColumn("ingredient_id")
		UnitIDColumn       = sqlite.IntegerColumn("unit_id")
		AmountColumn       = sqlite.FloatColumn("amount")
		SortOrderColumn    = sqlite.IntegerColumn("sort_order")
		allColumns         = sqlite.ColumnList{IDColumn, StepIDColumn, IngredientIDColumn, UnitIDColumn, AmountColumn, SortOrderColumn}
		mutableColumns     = sqlite.ColumnList{StepIDColumn, IngredientIDColumn, UnitIDColumn, AmountColumn, SortOrderColumn}
		defaultColumns     = sqlite.ColumnList{SortOrderColumn}
	)

	return recipeIngredientsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		StepID:       StepIDColumn,
		IngredientID: IngredientIDColumn,
		UnitID:       UnitIDColumn,
		Amount:       AmountColumn,
		SortOrder:    SortOrderColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
