//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var RecipeTags = newRecipeTagsTable("", "recipe_tags", "")

type recipeTagsTable struct {
	sqlite.Table

	// Columns
	RecipeID sqlite.ColumnInteger
	TagID    sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type RecipeTagsTable struct {
	recipeTagsTable

	EXCLUDED recipeTagsTable
}

// AS creates new RecipeTagsTable with assigned alias
func (a RecipeTagsTable) AS(alias string) *RecipeTagsTable {
	return newRecipeTagsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RecipeTagsTable with assigned schema name
func (a RecipeTagsTable) FromSchema(schemaName string) *RecipeTagsTable {
	return newRecipeTagsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RecipeTagsTable with assigned table prefix
func (a RecipeTagsTable) WithPrefix(prefix string) *RecipeTagsTable {
	return newRecipeTagsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RecipeTagsTable with assigned table suffix
func (a RecipeTagsTable) WithSuffix(suffix string) *RecipeTagsTable {
	return newRecipeTagsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRecipeTagsTable(schemaName, tableName, alias string) *RecipeTagsTable {
	return &RecipeTagsTable{
		recipeTagsTable: newRecipeTagsTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newRecipeTagsTableImpl("", "excluded", ""),
	}
}

func newRecipeTagsTableImpl(schemaName, tableName, alias string) recipeTagsTable {
	var (
		RecipeIDColumn = sqlite.IntegerColumn("recipe_id")
		TagIDColumn    = sqlite.IntegerColumn("tag_id")
		allColumns     = sqlite.ColumnList{RecipeIDColumn, TagIDColumn}
		mutableColumns = sqlite.ColumnList{}
		defaultColumns = sqlite.ColumnList{}
	)

	return recipeTagsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		RecipeID: RecipeIDColumn,
		TagID:    TagIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
