//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var RecipeSteps = newRecipeStepsTable("", "recipe_steps", "")

type recipeStepsTable struct {
	sqlite.Table

	// Columns
	ID           sqlite.ColumnInteger
	RecipeID     sqlite.ColumnInteger
	Instructions sqlite.ColumnString
	SortOrder    sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type RecipeStepsTable struct {
	recipeStepsTable

	EXCLUDED recipeStepsTable
}

// AS creates new RecipeStepsTable with assigned alias
func (a RecipeStepsTable) AS(alias string) *RecipeStepsTable {
	return newRecipeStepsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RecipeStepsTable with assigned schema name
func (a RecipeStepsTable) FromSchema(schemaName string) *RecipeStepsTable {
	return newRecipeStepsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RecipeStepsTable with assigned table prefix
func (a RecipeStepsTable) WithPrefix(prefix string) *RecipeStepsTable {
	return newRecipeStepsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RecipeStepsTable with assigned table suffix
func (a RecipeStepsTable) WithSuffix(suffix string) *RecipeStepsTable {
	return newRecipeStepsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRecipeStepsTable(schemaName, tableName, alias string) *RecipeStepsTable {
	return &RecipeStepsTable{
		recipeStepsTable: newRecipeStepsTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newRecipeStepsTableImpl("", "excluded", ""),
	}
}

func newRecipeStepsTableImpl(schemaName, tableName, alias string) recipeStepsTable {
	var (
		IDColumn           = sqlite.IntegerColumn("id")
		RecipeIDColumn     = sqlite.IntegerColumn("recipe_id")
		InstructionsColumn = sqlite.StringColumn("instructions")
		SortOrderColumn    = sqlite.IntegerColumn("sort_order")
		allColumns         = sqlite.ColumnList{IDColumn, RecipeIDColumn, InstructionsColumn, SortOrderColumn}
		mutableColumns     = sqlite.ColumnList{RecipeIDColumn, InstructionsColumn, SortOrderColumn}
		defaultColumns     = sqlite.ColumnList{SortOrderColumn}
	)

	return recipeStepsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		RecipeID:     RecipeIDColumn,
		Instructions: InstructionsColumn,
		SortOrder:    SortOrderColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
