//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Recipes = newRecipesTable("", "recipes", "")

type recipesTable struct {
	sqlite.Table

	// Columns
	ID          sqlite.ColumnInteger
	Name        sqlite.ColumnString
	Servings    sqlite.ColumnInteger
	Minutes     sqlite.ColumnInteger
	Description sqlite.ColumnString
	CreatedBy   sqlite.ColumnInteger
	CreatedAt   sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type RecipesTable struct {
	recipesTable

	EXCLUDED recipesTable
}

// AS creates new RecipesTable with assigned alias
func (a RecipesTable) AS(alias string) *RecipesTable {
	return newRecipesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RecipesTable with assigned schema name
func (a RecipesTable) FromSchema(schemaName string) *RecipesTable {
	return newRecipesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RecipesTable with assigned table prefix
func (a RecipesTable) WithPrefix(prefix string) *RecipesTable {
	return newRecipesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RecipesTable with assigned table suffix
func (a RecipesTable) WithSuffix(suffix string) *RecipesTable {
	return newRecipesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRecipesTable(schemaName, tableName, alias string) *RecipesTable {
	return &RecipesTable{
		recipesTable: newRecipesTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newRecipesTableImpl("", "excluded", ""),
	}
}

func newRecipesTableImpl(schemaName, tableName, alias string) recipesTable {
	var (
		IDColumn          = sqlite.IntegerColumn("id")
		NameColumn        = sqlite.StringColumn("name")
		ServingsColumn    = sqlite.IntegerColumn("servings")
		MinutesColumn     = sqlite.IntegerColumn("minutes")
		DescriptionColumn = sqlite.StringColumn("description")
		CreatedByColumn   = sqlite.IntegerColumn("created_by")
		CreatedAtColumn   = sqlite.TimestampColumn("created_at")
		allColumns        = sqlite.ColumnList{IDColumn, NameColumn, ServingsColumn, MinutesColumn, DescriptionColumn, CreatedByColumn, CreatedAtColumn}
		mutableColumns    = sqlite.ColumnList{NameColumn, ServingsColumn, MinutesColumn, DescriptionColumn, CreatedByColumn, CreatedAtColumn}
		defaultColumns    = sqlite.ColumnList{CreatedAtColumn}
	)

	return recipesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Name:        NameColumn,
		Servings:    ServingsColumn,
		Minutes:     MinutesColumn,
		Description: DescriptionColumn,
		CreatedBy:   CreatedByColumn,
		CreatedAt:   CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
