//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var ShoppingListItems = newShoppingListItemsTable("", "shopping_list_items", "")

type shoppingListItemsTable struct {
	sqlite.Table

	// Columns
	ID             sqlite.ColumnInteger
	ShoppingListID sqlite.ColumnInteger
	Ingredient     sqlite.ColumnString
	Quantity       sqlite.ColumnString
	Unit           sqlite.ColumnString
	Done           sqlite.ColumnBool
	SortOrder      sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ShoppingListItemsTable struct {
	shoppingListItemsTable

	EXCLUDED shoppingListItemsTable
}

// AS creates new ShoppingListItemsTable with assigned alias
func (a ShoppingListItemsTable) AS(alias string) *ShoppingListItemsTable {
	return newShoppingListItemsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ShoppingListItemsTable with assigned schema name
func (a ShoppingListItemsTable) FromSchema(schemaName string) *ShoppingListItemsTable {
	return newShoppingListItemsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ShoppingListItemsTable with assigned table prefix
func (a ShoppingListItemsTable) WithPrefix(prefix string) *ShoppingListItemsTable {
	return newShoppingListItemsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ShoppingListItemsTable with assigned table suffix
func (a ShoppingListItemsTable) WithSuffix(suffix string) *ShoppingListItemsTable {
	return newShoppingListItemsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newShoppingListItemsTable(schemaName, tableName, alias string) *ShoppingListItemsTable {
	return &ShoppingListItemsTable{
		shoppingListItemsTable: newShoppingListItemsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newShoppingListItemsTableImpl("", "excluded", ""),
	}
}

func newShoppingListItemsTableImpl(schemaName, tableName, alias string) shoppingListItemsTable {
	var (
		IDColumn             = sqlite.IntegerColumn("id")
		ShoppingListIDColumn = sqlite.IntegerColumn("shopping_list_id")
		IngredientColumn     = sqlite.StringColumn("ingredient")
		QuantityColumn       = sqlite.StringColumn("quantity")
		UnitColumn           = sqlite.StringColumn("unit")
		DoneColumn           = sqlite.BoolColumn("done")
		SortOrderColumn      = sqlite.IntegerColumn("sort_order")
		allColumns           = sqlite.ColumnList{IDColumn, ShoppingListIDColumn, IngredientColumn, QuantityColumn, UnitColumn, DoneColumn, SortOrderColumn}
		mutableColumns       = sqlite.ColumnList{ShoppingListIDColumn, IngredientColumn, QuantityColumn, UnitColumn, DoneColumn, SortOrderColumn}
		defaultColumns       = sqlite.ColumnList{DoneColumn, SortOrderColumn}
	)

	return shoppingListItemsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		ShoppingListID: ShoppingListIDColumn,
		Ingredient:     IngredientColumn,
		Quantity:       QuantityColumn,
		Unit:           UnitColumn,
		Done:           DoneColumn,
		SortOrder:      SortOrderColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
