//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var ShoppingLists = newShoppingListsTable("", "shopping_lists", "")

type shoppingListsTable struct {
	sqlite.Table

	// Columns
	ID     sqlite.ColumnInteger
	UserID sqlite.ColumnInteger
	Name   sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type ShoppingListsTable struct {
	shoppingListsTable

	EXCLUDED shoppingListsTable
}

// AS creates new ShoppingListsTable with assigned alias
func (a ShoppingListsTable) AS(alias string) *ShoppingListsTable {
	return newShoppingListsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ShoppingListsTable with assigned schema name
func (a ShoppingListsTable) FromSchema(schemaName string) *ShoppingListsTable {
	return newShoppingListsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ShoppingListsTable with assigned table prefix
func (a ShoppingListsTable) WithPrefix(prefix string) *ShoppingListsTable {
	return newShoppingListsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ShoppingListsTable with assigned table suffix
func (a ShoppingListsTable) WithSuffix(suffix string) *ShoppingListsTable {
	return newShoppingListsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newShoppingListsTable(schemaName, tableName, alias string) *ShoppingListsTable {
	return &ShoppingListsTable{
		shoppingListsTable: newShoppingListsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newShoppingListsTableImpl("", "excluded", ""),
	}
}

func newShoppingListsTableImpl(schemaName, tableName, alias string) shoppingListsTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		UserIDColumn   = sqlite.IntegerColumn("user_id")
		NameColumn     = sqlite.StringColumn("name")
		allColumns     = sqlite.ColumnList{IDColumn, UserIDColumn, NameColumn}
		mutableColumns = sqlite.ColumnList{UserIDColumn, NameColumn}
		defaultColumns = sqlite.ColumnList{NameColumn}
	)

	return shoppingListsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:     IDColumn,
		UserID: UserIDColumn,
		Name:   NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
