//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	AtlasSchemaRevisions = AtlasSchemaRevisions.FromSchema(schema)
	IngredientNutrients = IngredientNutrients.FromSchema(schema)
	Ingredients = Ingredients.FromSchema(schema)
	MealPlan = MealPlan.FromSchema(schema)
	Nutrients = Nutrients.FromSchema(schema)
	PasswordResets = PasswordResets.FromSchema(schema)
	Permissions = Permissions.FromSchema(schema)
	RecipeImages = RecipeImages.FromSchema(schema)
	RecipeIngredients = RecipeIngredients.FromSchema(schema)
	RecipeSteps = RecipeSteps.FromSchema(schema)
	RecipeTags = RecipeTags.FromSchema(schema)
	Recipes = Recipes.FromSchema(schema)
	RolePermissions = RolePermissions.FromSchema(schema)
	Roles = Roles.FromSchema(schema)
	ShoppingListItems = ShoppingListItems.FromSchema(schema)
	ShoppingLists = ShoppingLists.FromSchema(schema)
	Tags = Tags.FromSchema(schema)
	Units = Units.FromSchema(schema)
	UserRegistrations = UserRegistrations.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
