//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Units = newUnitsTable("", "units", "")

type unitsTable struct {
	sqlite.Table

	// Columns
	ID     sqlite.ColumnInteger
	Symbol sqlite.ColumnString
	Name   sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type UnitsTable struct {
	unitsTable

	EXCLUDED unitsTable
}

// AS creates new UnitsTable with assigned alias
func (a UnitsTable) AS(alias string) *UnitsTable {
	return newUnitsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UnitsTable with assigned schema name
func (a UnitsTable) FromSchema(schemaName string) *UnitsTable {
	return newUnitsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UnitsTable with assigned table prefix
func (a UnitsTable) WithPrefix(prefix string) *UnitsTable {
	return newUnitsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UnitsTable with assigned table suffix
func (a UnitsTable) WithSuffix(suffix string) *UnitsTable {
	return newUnitsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUnitsTable(schemaName, tableName, alias string) *UnitsTable {
	return &UnitsTable{
		unitsTable: newUnitsTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newUnitsTableImpl("", "excluded", ""),
	}
}

func newUnitsTableImpl(schemaName, tableName, alias string) unitsTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		SymbolColumn   = sqlite.StringColumn("symbol")
		NameColumn     = sqlite.StringColumn("name")
		allColumns     = sqlite.ColumnList{IDColumn, SymbolColumn, NameColumn}
		mutableColumns = sqlite.ColumnList{SymbolColumn, NameColumn}
		defaultColumns = sqlite.ColumnList{}
	)

	return unitsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:     IDColumn,
		Symbol: SymbolColumn,
		Name:   NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
