//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var UserRegistrations = newUserRegistrationsTable("", "user_registrations", "")

type userRegistrationsTable struct {
	sqlite.Table

	// Columns
	UserID    sqlite.ColumnInteger
	Token     sqlite.ColumnString
	CreatedAt sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type UserRegistrationsTable struct {
	userRegistrationsTable

	EXCLUDED userRegistrationsTable
}

// AS creates new UserRegistrationsTable with assigned alias
func (a UserRegistrationsTable) AS(alias string) *UserRegistrationsTable {
	return newUserRegistrationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserRegistrationsTable with assigned schema name
func (a UserRegistrationsTable) FromSchema(schemaName string) *UserRegistrationsTable {
	return newUserRegistrationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserRegistrationsTable with assigned table prefix
func (a UserRegistrationsTable) WithPrefix(prefix string) *UserRegistrationsTable {
	return newUserRegistrationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserRegistrationsTable with assigned table suffix
func (a UserRegistrationsTable) WithSuffix(suffix string) *UserRegistrationsTable {
	return newUserRegistrationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserRegistrationsTable(schemaName, tableName, alias string) *UserRegistrationsTable {
	return &UserRegistrationsTable{
		userRegistrationsTable: newUserRegistrationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newUserRegistrationsTableImpl("", "excluded", ""),
	}
}

func newUserRegistrationsTableImpl(schemaName, tableName, alias string) userRegistrationsTable {
	var (
		UserIDColumn    = sqlite.IntegerColumn("user_id")
		TokenColumn     = sqlite.StringColumn("token")
		CreatedAtColumn = sqlite.TimestampColumn("created_at")
		allColumns      = sqlite.ColumnList{UserIDColumn, TokenColumn, CreatedAtColumn}
		mutableColumns  = sqlite.ColumnList{TokenColumn, CreatedAtColumn}
		defaultColumns  = sqlite.ColumnList{CreatedAtColumn}
	)

	return userRegistrationsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:    UserIDColumn,
		Token:     TokenColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
