//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Users = newUsersTable("", "users", "")

type usersTable struct {
	sqlite.Table

	// Columns
	ID           sqlite.ColumnInteger
	Email        sqlite.ColumnString
	PasswordHash sqlite.ColumnString
	IsConfirmed  sqlite.ColumnBool
	RoleID       sqlite.ColumnInteger
	CreatedAt    sqlite.ColumnTimestamp
	Locale       sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type UsersTable struct {
	usersTable

	EXCLUDED usersTable
}

// AS creates new UsersTable with assigned alias
func (a UsersTable) AS(alias string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UsersTable with assigned schema name
func (a UsersTable) FromSchema(schemaName string) *UsersTable {
	return newUsersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UsersTable with assigned table prefix
func (a UsersTable) WithPrefix(prefix string) *UsersTable {
	return newUsersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UsersTable with assigned table suffix
func (a UsersTable) WithSuffix(suffix string) *UsersTable {
	return newUsersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUsersTable(schemaName, tableName, alias string) *UsersTable {
	return &UsersTable{
		usersTable: newUsersTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newUsersTableImpl("", "excluded", ""),
	}
}

func newUsersTableImpl(schemaName, tableName, alias string) usersTable {
	var (
		IDColumn           = sqlite.IntegerColumn("id")
		EmailColumn        = sqlite.StringColumn("email")
		PasswordHashColumn = sqlite.StringColumn("password_hash")
		IsConfirmedColumn  = sqlite.BoolColumn("is_confirmed")
		RoleIDColumn       = sqlite.IntegerColumn("role_id")
		CreatedAtColumn    = sqlite.TimestampColumn("created_at")
		LocaleColumn       = sqlite.StringColumn("locale")
		allColumns         = sqlite.ColumnList{IDColumn, EmailColumn, PasswordHashColumn, IsConfirmedColumn, RoleIDColumn, CreatedAtColumn, LocaleColumn}
		mutableColumns     = sqlite.ColumnList{EmailColumn, PasswordHashColumn, IsConfirmedColumn, RoleIDColumn, CreatedAtColumn, LocaleColumn}
		defaultColumns     = sqlite.ColumnList{IsConfirmedColumn, CreatedAtColumn, LocaleColumn}
	)

	return usersTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		Email:        EmailColumn,
		PasswordHash: PasswordHashColumn,
		IsConfirmed:  IsConfirmedColumn,
		RoleID:       RoleIDColumn,
		CreatedAt:    CreatedAtColumn,
		Locale:       LocaleColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
